### ISSUE TITLE
Distância de entrega (semana)

### ISSUE THREAD

**Issue by ThiagoCavalcantiSilva** [lmtsufape/ecommerce-gestao-agricola-api#16]
Vendedor pode **adicionar/visualizar/alterar** a distância máxima para efetuar a entrega durante a semana no sistema.

**Comment by luiz-davi** [comment]
Criar modelo e migração de cep, bairro e rua.
Criar um seeder, com base num arquivo fornecido, relacionando essas informações com regiões especificadas.
Criar modelo e migração de região.
Modificar crud de endereços, relacionando o endereço a essas demais informações.
Criar endpoints que para listagem dessas informações(cep, bairro, rua e região).
